USE sakila;

-- 1. List the number of films per category.
SELECT category.category_id, category.name, COUNT(film_category.film_id) 
FROM category
LEFT JOIN film_category ON category.category_id = film_category.category_id
GROUP BY category.category_id, category.name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT store.store_id, city.city, country.country
FROM store
LEFT JOIN address ON store.address_id = address.address_id
LEFT JOIN city ON address.city_id = city.city_id
LEFT JOIN country ON city.country_id = country.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount) AS total_revenue
FROM store
LEFT JOIN customer ON store.store_id = customer.store_id
LEFT JOIN rental ON customer.customer_id = rental.customer_id
LEFT JOIN payment ON rental.rental_id = payment.rental_id
GROUP BY 
store.store_id;

-- 4. Determine the average running time of films for each category.
SELECT category.name, ROUND(AVG(film.length),2) AS avg_running_time
FROM category
RIGHT JOIN film_category ON category.category_id = film_category.category_id
LEFT JOIN film ON film_category.film_id = film_category.film_id
GROUP BY 
category.name;



